### ISSUE TITLE
text box doesn't adjust for multi-line text

### ISSUE THREAD

**Issue by samcammarata** [aestheticianlabs/listcord#3]
![image](https://user-images.githubusercontent.com/32913373/119506509-fb31d800-bd3b-11eb-8b46-dafd343e1262.png)

**Comment by magnoahlia** [comment]
Nice catch! It looks like the issue is the display span when the text isn't being edited. Setting `overflow: hidden;` on the parent div should do the trick for now, although maybe we don't need the display span at all. Fixing this would be a great first PR 😉
